### ISSUE TITLE
建议增加对TBAlertController的说明.

### ISSUE THREAD

**Issue by zzgo** [yulingtianxia/TBActionSheet#12]
首先非常谢谢作者的分享.
不过有一点点小建议.整个readme的说明基本上针对TBActionSheet的,我是自己在对应头文件看api使用TBAlertController .
而去读你的博客又相对没那么"快".

**Comment by yulingtianxia** [comment]
感谢你提的意见，已经更新了 readme，在末尾增加了对 TBAlertController 的简介。
