### ISSUE TITLE
你这个库在iOS8 下面出现这种错误

### ISSUE THREAD

**Issue by nightwolf-chen** [yulingtianxia/TBActionSheet#14]
dyld: Symbol not found: ___NSArray0__
  Referenced from: /private/var/mobile/Containers/Bundle/Application/4C8312C8-9F92-4B31-9CC8-4217A04AB036/ContactLive.app/Frameworks/TBActionSheetKit.framework/TBActionSheetKit (which was built for iOS 9.3)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /private/var/mobile/Containers/Bundle/Application/4C8312C8-9F92-4B31-9CC8-4217A04AB036/ContactLive.app/Frameworks/TBActionSheetKit.framework/TBActionSheetKit

**Comment by nightwolf-chen** [comment]
我直接下载release的framework或者使用carthage都会有这个问题，估计是framework deployment target设置为了9.3。我自己下源码改了一下deployment target就没问题了。

**Comment by yulingtianxia** [comment]
@nightwolf-chen 对的，我已经把9.3改成8.0了
