### ISSUE TITLE
TBActionButton的样式自定义没有放出来呀

### ISSUE THREAD

**Issue by hydyy** [yulingtianxia/TBActionSheet#15]
想改按下背景色，不知道怎么改

**Comment by yulingtianxia** [comment]
@hydyy 在 TBActionSheet 中可以改环境色，ambientColor

**Comment by hydyy** [comment]
我设置环境色是白色，然后我想改变按钮按下的颜色。


原始邮件
发件人:杨萧玉notifications@github.com
收件人:yulingtianxia/TBActionSheetTBActionSheet@noreply.github.com
抄送:Adamhouyaodong@qq.com; Mentionmention@noreply.github.com
发送时间:2017年2月16日(周四) 22:08
主题:Re: [yulingtianxia/TBActionSheet] TBActionButton的样式自定义没有放出来呀 (#15)


@hydyy 在 TBActionSheet 中可以改环境色，ambientColor

**Comment by yulingtianxia** [comment]
@hydyy `TBActionButton` 中的 `highlightedColor` 属性可以满足你的需求，不过目前还没有直接开放获取  `TBActionButton` 的接口，我稍后更新下

**Comment by hydyy** [comment]
okok thx!!


原始邮件
发件人:杨萧玉notifications@github.com
收件人:yulingtianxia/TBActionSheetTBActionSheet@noreply.github.com
抄送:Adamhouyaodong@qq.com; Mentionmention@noreply.github.com
发送时间:2017年2月18日(周六) 12:32
主题:Re: [yulingtianxia/TBActionSheet] TBActionButton的样式自定义没有放出来呀 (#15)


@hydyy TBActionButton 中的 highlightedColor 属性可以满足你的需求，不过目前还没有直接开放获取 TBActionButton 的接口，我稍后更新下

**Comment by yulingtianxia** [comment]
@hydyy 已经更新到 1.5.0

**Comment by hydyy** [comment]
哈哈 真效率！ 给赞！
