### ISSUE TITLE
循环引用和闪屏问题  retain cycle & screenshot blinking

### ISSUE THREAD

**Issue by Icelolli** [yulingtianxia/TBActionSheet#17]
1. UIImage *(^cutOriginalBackgroundImageInRect)(CGRect frame) 会引起TBBlurEffectBlock被添加到self.blurBlocks后引起循环引用

2. [view drawViewHierarchyInRect:self.bounds afterScreenUpdates:YES]; 会造成截屏时出现闪屏现象，建议改成 afterScreenUpdates:NO

**Comment by yulingtianxia** [comment]
@Icelolli 1. cutOriginalBackgroundImageInRect是在方法内部定义的局部变量，不会引起循环引用
2. 你说的闪屏现象在真机没有发现，麻烦提供下你的运行环境

**Comment by yulingtianxia** [comment]
@Icelolli 感谢指出的问题，闪屏现象之前在 iOS 10模拟器上出现过，但是真机并没有出现，想问下你出现的场景和环境是怎样的呢？

**Comment by Icelolli** [comment]
确实在真机上没有出现，我也是在模拟器上看到的

**Comment by yulingtianxia** [comment]
1. 循环引用已解决
2. #7 重复 issue，最新版本模拟器 OK，老版本的 iOS 10模拟器会有此 bug
