### ISSUE TITLE
横屏引起崩溃.

### ISSUE THREAD

**Issue by zzgo** [yulingtianxia/TBActionSheet#18]
友盟提示是:
Supported orientations has no common orientation with the application, and [MVRewardViewController shouldAutorotate] is returning YES
(null)

然后定位代码,是我调用了`TBAlertController`去 present 引起的.
因为还牵扯到一个第三方的视频广告 SDK, 我这里不知道该怎么配合排查问题?
看看到底是 TBActionSheet 还是我自己哪里的问题.

**Comment by yulingtianxia** [comment]
@zzgo 在我的 Demo 里旋转是 OK 的，你可以 debug 调试下

**Comment by zzgo** [comment]
好的,我现在猜测是上面视频广告改变了横竖屏的一些东西,然后 presnet 冲突了.
关了 issues,打扰了.
