### ISSUE TITLE
TBActionSheet 消失之后，创建的window没有销毁

### ISSUE THREAD

**Issue by leoliuyt** [yulingtianxia/TBActionSheet#20]
TBActionSheet 消失之后，创建的window没有销毁，导致一些其他第三的loading 无法显示，应该在- (void)close和- (void)buttonTapped:(TBActionButton *)sender中 添加下面标注的一行代码
self.window.rootViewController = nil;
self.window = nil;//(应该添加的)
[self.previousKeyWindow makeKeyAndVisible];

**Comment by yulingtianxia** [comment]
fixed in 1.5.3
