### ISSUE TITLE
自定义视图的横线高度有问题

### ISSUE THREAD

**Issue by git4jwb** [yulingtianxia/TBActionSheet#22]
本该在自定义视图底部的横线，显示到了自定义视图的顶部了

**Comment by git4jwb** [comment]
没有title和message，只有自定义视图的时候

**Comment by yulingtianxia** [comment]
@git4jwb 麻烦提供下复现 bug 的代码

**Comment by yulingtianxia** [comment]
![img_2729](https://cloud.githubusercontent.com/assets/433320/26450799/c3f47f26-418b-11e7-97ab-f9c501f73ded.PNG)
@git4jwb 我这里没有复现你说的情况，请问更新到最新版了么？
