### ISSUE TITLE
Crash when  snapshot

### ISSUE THREAD

**Issue by Bluelich** [yulingtianxia/TBActionSheet#26]
Code:
```
- (UIImage *)screenShotRect:(CGRect)aRect
```

```
// Use this method to render a snapshot of the view hierarchy into the current context. 
Returns NO if the snapshot is missing image data, YES if the snapshot is complete.
 Calling this method from layoutSubviews while the current transaction is committing 
will capture what is currently displayed regardless if afterUpdates is YES.
- (BOOL)drawViewHierarchyInRect:(CGRect)rect afterScreenUpdates:(BOOL)afterUpdates NS_AVAILABLE_IOS(7_0);
```
如果在截图的过程中,视图层级中的某个view被释放掉,这个方法可能会导致崩溃
目前仅在iOS 11.0 (15A5318g)上遇到过2次,希望能尽快修复!

[issues on stackoverflow](https://stackoverflow.com/questions/19903665/uigraphics-crashes-on-ios-7)

**Comment by yulingtianxia** [comment]
@Bluelich 能附上 crash 堆栈信息么

**Comment by Bluelich** [comment]
<img width="910" alt="32d1eccb-a68e-412a-ae22-1d7642a3647d" src="https://user-images.githubusercontent.com/8563315/28812059-71d5cabe-76c5-11e7-9092-afff5f984633.png">
