### ISSUE TITLE
Dismiss actionsheet from custom view

### ISSUE THREAD

**Issue by Amirnadi** [yulingtianxia/TBActionSheet#27]
I want to add button in custom view and then on that button click, dismiss the action sheet.
I tried hard but no progress 👎  please if you can help me with it. Thankyou

**Comment by yulingtianxia** [comment]
@Amirnadi You can use `close` method.

**Comment by Amirnadi** [comment]
I am done with it. Thankyou (Y)

**Comment by yulingtianxia** [comment]
@Amirnadi You're welcome.
