### ISSUE TITLE
bigFragment 参数能否暴露出来？

### ISSUE THREAD

**Issue by change2hao** [yulingtianxia/TBActionSheet#33]
你好，请问 bigFragment 参数能否暴露出来？这样更方便进行间隙的设置

**Comment by yulingtianxia** [comment]
https://github.com/yulingtianxia/TBActionSheet/commit/4d88a7ccce2718c3a3207308617ba2eb8e7d69d7
done
@change2hao

**Comment by change2hao** [comment]
@yulingtianxia 赞，但是目前从 https://cocoapods.org 中搜索到的最新版本还是 1.6.2？

**Comment by yulingtianxia** [comment]
@change2hao  CocoaPods 有 bug，不支持 Xcode 10.1 beta，官方号称修复了其实还是有问题。所以我这段时间更新不了 pods 了。

**Comment by yulingtianxia** [comment]
@change2hao CocoaPods 1.6.4 已经更新

**Comment by change2hao** [comment]
🎉🎉🎉 @yulingtianxia
