### ISSUE TITLE
destructiveButton位置

### ISSUE THREAD

**Issue by NoahJJ** [yulingtianxia/TBActionSheet#38]
兄弟，这个destructiveButton的位置不可以调吗，这样体验很不好啊，删除一般不会放在第一个啊

**Comment by yulingtianxia** [comment]
@NoahJJ 这取决于添加 Action 的顺序

**Comment by NoahJJ** [comment]
> @NoahJJ 这取决于添加 Action 的顺序

我使用的是TBAciionSheet

TBActionSheet *sheet  = [[TBActionSheet alloc] initWithTitle:item.title message:@"" delegate:nil cancelButtonTitle:@"取消" destructiveButtonTitle:@"删除" otherButtonTitles:@"重命名",@"移动",nil];

**Comment by yulingtianxia** [comment]
> > @NoahJJ 这取决于添加 Action 的顺序
> 
> 我使用的是TBActionSheet
> 
> TBActionSheet *sheet = [[TBActionSheet alloc] initWithTitle:item.title message:@"" delegate:nil cancelButtonTitle:@"取消" destructiveButtonTitle:@"删除" otherButtonTitles:@"重命名",@"移动",nil];

这里的行为是复刻了系统的 `UIActionSheet`:
```
UIActionSheet *sheet = [[UIActionSheet alloc] initWithTitle:@"title" delegate:self cancelButtonTitle:@"取消" destructiveButtonTitle:@"删除" otherButtonTitles:@"重命名",@"移动", nil];
    [sheet showInView:self.view];
```

**Comment by NoahJJ** [comment]
> > > @NoahJJ 这取决于添加 Action 的顺序
> > 
> > 
> > 我使用的是TBActionSheet
> > TBActionSheet *sheet = [[TBActionSheet alloc] initWithTitle:item.title message:@"" delegate:nil cancelButtonTitle:@"取消" destructiveButtonTitle:@"删除" otherButtonTitles:@"重命名",@"移动",nil];
> 
> 这里的行为是复刻了系统的 `UIActionSheet`:
> 
> ```
> UIActionSheet *sheet = [[UIActionSheet alloc] initWithTitle:@"title" delegate:self cancelButtonTitle:@"取消" destructiveButtonTitle:@"删除" otherButtonTitles:@"重命名",@"移动", nil];
>     [sheet showInView:self.view];
> ```

可以
        TBActionSheet *shee = [[TBActionSheet alloc] init];
        [shee addButtonWithTitle:@"重命名" style:TBActionButtonStyleDefault];
        [shee addButtonWithTitle:@"移动" style:TBActionButtonStyleDefault];
        [shee addButtonWithTitle:@"删除" style:TBActionButtonStyleDestructive];
        [shee addButtonWithTitle:@"取消" style:TBActionButtonStyleCancel];
这样可以了

**Comment by yulingtianxia** [comment]
对的，所以我也提供了更现代化的API，可以添加action控制顺序。复刻老版本API只是为了方便快速迁移旧代码。
