### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by icharlie2014** [yulingtianxia/TBActionSheet#6]
我测试TBAlertController时候

出现了内存泄露，检测工具MLeaksFinder
请看86~97行
https://github.com/yulingtianxia/TBActionSheet/blob/master/Example/TBAlertControllerDemo/ViewController.m
下面贴出代码
```javascript
    TBAlertController *controller = [TBAlertController alertControllerWithTitle:@"TBAlertController" message:@"AlertStyle" preferredStyle:TBAlertControllerStyleActionSheet];
    TBAlertAction *clickme = [TBAlertAction actionWithTitle:@"点我" style: TBAlertActionStyleDefault handler:^(TBAlertAction * _Nonnull action) {
        NSLog(@"%@ ",action.title);
    }];
    TBAlertAction *cancel = [TBAlertAction actionWithTitle:@"取消" style: TBAlertActionStyleCancel handler:^(TBAlertAction * _Nonnull action) {
        NSLog(@"%@ ",action.title);
    }];
    [controller addAction:clickme];
    [controller addAction:cancel];
    [self presentViewController:controller animated:YES completion:nil];
```
![simulator screen shot 2016 8 24 6 27 36](https://cloud.githubusercontent.com/assets/8463936/17927522/ab2bc228-6a28-11e6-885d-63f330f20219.png)

**Comment by yulingtianxia** [comment]
@icharlie2014 请问系统版本是什么呢？

**Comment by icharlie2014** [comment]
![2016-08-25 7 42 24](https://cloud.githubusercontent.com/assets/8463936/17967841/190de0f4-6afc-11e6-9197-9d96a918bfa9.png)

**Comment by yulingtianxia** [comment]
@icharlie2014 我用最新版本（1.4.3）测试并没有内存泄露啊，检测工具MLeaksFinder。看你给的代码示例感觉是很旧的版本，新的代码早已加上 self.leakTest

**Comment by tianglin** [comment]
@yulingtianxia 很感谢你的分享，我在 Podfile 中是这样添加的: pod 'TBActionSheet'
不过显示的是 1.4.1 版本，怎么不是最新的 1.4.3 呢？

**Comment by tianglin** [comment]
改成 pod 'TBActionSheet', :git => 'https://github.com/yulingtianxia/TBActionSheet.git' 就ok了。

是吗？

**Comment by yulingtianxia** [comment]
@tianglin 你可能需要更新下本地的 pod 数据，`pod setup` 后再 `pod install`

**Comment by tianglin** [comment]
@yulingtianxia 挂梯子 `pod setup` 都一直没有反应，奇怪~

**Comment by skyline75489** [comment]
@tianglin  `pod setup --verbose`

**Comment by tianglin** [comment]
@skyline75489 谢谢，我试一下看行不行。

**Comment by yulingtianxia** [comment]
内存泄露早已解决
