### ISSUE TITLE
Carthage Support?

### ISSUE THREAD

**Issue by skyline75489** [yulingtianxia/TBActionSheet#8]

**Comment by yulingtianxia** [comment]
You ask me support or not, I must say I support.

**Comment by skyline75489** [comment]
👍

**Comment by skyline75489** [comment]
不过讲道理写 Framework project 还是有点麻烦的...

**Comment by skyline75489** [comment]
原来 Framework 藏在 Example 文件夹里面，搞得我以为不支持 Carthage，我的锅...

**Comment by yulingtianxia** [comment]
@skyline75489 哈哈，看来 readme 太长果真没人看啊
